[features]
seeds = false
skip-lint = false

[programs.localnet]
arcan_router = "ArcRtr1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx jest"
